export const arrayWithAttractionsForSearchInput = [
  "Burj Khalifa",
  "Dubai Marina",
  "The Palm Jumeirah",
  "Dubai Mall",
  "Jumeirah Beach",
  "The Dubai Fountain",
  "Old Dubai",
  "Dubai Creek",
  "Miracle Garden",
  "Global Village",
  "Ski Dubai",
  "IMG Worlds of Adventure",
  "Dubai Frame",
  "Atlantis, The Palm",
  "Jumeirah Mosque",
  "Dubai Opera",
  "Madinat Jumeirah",
  "Dubai Aquarium & Underwater Zoo",
  "Dubai Miracle Garden",
  "JBR Beach",
  "Deira Gold Souk",
  "The Lost Chambers Aquarium",
  "Dubai Parks and Resorts",
  "Dubai Garden Glow",
  "Dubai Butterfly Garden",
  "Palm Islands",
  "Dubai Autodrome",
  "Dubai Museum",
  "Wild Wadi Waterpark",
  "Dubai Desert Safari",
];
