export const GET_MAIN_DATA_REQUEST: "GET_MAIN_DATA_REQUEST" =
  "GET_MAIN_DATA_REQUEST";
export const GET_MAIN_DATA_SUCCESS: "GET_MAIN_DATA_SUCCESS" =
  "GET_MAIN_DATA_SUCCESS";
export const GET_MAIN_DATA_FAILED: "GET_MAIN_DATA_FAILED" =
  "GET_MAIN_DATA_FAILED";
export const SET_MODAL_STATE: "SET_MODAL_STATE" = "SET_MODAL_STATE";
