export const GET_RESERVATION_DATA_REQUEST: "GET_RESERVATION_DATA_REQUEST" =
  "GET_RESERVATION_DATA_REQUEST";
export const GET_RESERVATION_DATA_SUCCESS: "GET_RESERVATION_DATA_SUCCESS" =
  "GET_RESERVATION_DATA_SUCCESS";
export const GET_RESERVATION_DATA_FAILED: "GET_RESERVATION_DATA_FAILED" =
  "GET_RESERVATION_DATA_FAILED";

export const SET_RESERVATION_MODAL_OPENED: "SET_RESERVATION_MODAL_OPENED" =
  "SET_RESERVATION_MODAL_OPENED";
export const SET_RESERVATION_MODAL_CLOSED: "SET_RESERVATION_MODAL_CLOSED" =
  "SET_RESERVATION_MODAL_CLOSED";

export const SET_CURRENT_OPENED_MODAL: "SET_CURRENT_OPENED_MODAL" =
  "SET_CURRENT_OPENED_MODAL";
export const SET_CURRENT_MODAL_DATA: "SET_CURRENT_MODAL_DATA" =
  "SET_CURRENT_MODAL_DATA";

export const SET_RESERVATION_FORM_STATE_RETURN_DATE: "SET_RESERVATION_FORM_STATE_RETURN_DATE" =
  "SET_RESERVATION_FORM_STATE_RETURN_DATE";
export const SET_RESERVATION_FORM_STATE_RETURN_TIME: "SET_RESERVATION_FORM_STATE_RETURN_TIME" =
  "SET_RESERVATION_FORM_STATE_RETURN_TIME";
export const SET_RESERVATION_FORM_STATE_ADULTS: "SET_RESERVATION_FORM_STATE_ADULTS" =
  "SET_RESERVATION_FORM_STATE_ADULTS";
export const SET_RESERVATION_FORM_STATE_KIDS: "SET_RESERVATION_FORM_STATE_KIDS" =
  "SET_RESERVATION_FORM_STATE_KIDS";
export const SET_RESERVATION_FORM_STATE_FOOD: "SET_RESERVATION_FORM_STATE_FOOD" =
  "SET_RESERVATION_FORM_STATE_FOOD";
export const SET_RESERVATION_FORM_STATE_TRANSFER: "SET_RESERVATION_FORM_STATE_TRANSFER" =
  "SET_RESERVATION_FORM_STATE_TRANSFER";

export const SET_RESERVATION_LABELS_STATE_RETURN_DATE: "SET_RESERVATION_LABELS_STATE_RETURN_DATE" =
  "SET_RESERVATION_LABELS_STATE_RETURN_DATE";
export const SET_RESERVATION_LABELS_STATE_RETURN_TIME: "SET_RESERVATION_LABELS_STATE_RETURN_TIME" =
  "SET_RESERVATION_LABELS_STATE_RETURN_TIME";
export const SET_RESERVATION_LABELS_STATE_ADULTS: "SET_RESERVATION_LABELS_STATE_ADULTS" =
  "SET_RESERVATION_LABELS_STATE_ADULTS";
export const SET_RESERVATION_LABELS_STATE_KIDS: "SET_RESERVATION_LABELS_STATE_KIDS" =
  "SET_RESERVATION_LABELS_STATE_KIDS";
export const SET_RESERVATION_LABELS_STATE_FOOD: "SET_RESERVATION_LABELS_STATE_FOOD" =
  "SET_RESERVATION_LABELS_STATE_FOOD";
export const SET_RESERVATION_LABELS_STATE_TRANSFER: "SET_RESERVATION_LABELS_STATE_TRANSFER" =
  "SET_RESERVATION_LABELS_STATE_TRANSFER";

export const SET_TOTAL_FORM_DATA: "SET_TOTAL_FORM_DATA" = "SET_TOTAL_FORM_DATA";
